version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event
    networks:
      - nest-net

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    environment:
      - MONGO_URI=mongodb://root:1234@mongodb:27017/auth?authSource=admin
    depends_on:
      - mongodb
    networks:
      - nest-net

  event:
    build:
      context: ./event
      dockerfile: Dockerfile
    ports:
      - '4002:4002'
    environment:
      - MONGO_URI=mongodb://root:1234@mongodb:27017/event?authSource=admin
    depends_on:
      - mongodb
    networks:
      - nest-net

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - nest-net

networks:
  nest-net:
    driver: bridge
