version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - '3000:3000'
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - auth
      - event
    networks:
      - nest-net

  auth:
    build: ./auth
    ports:
      - '4001:4001'
    volumes:
      - ./auth:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:1234@mongodb:27017/auth?authSource=admin
    networks:
      - nest-net

  event:
    build: ./event
    ports:
      - '4002:4002'
    volumes:
      - ./event:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:1234@mongodb:27017/event?authSource=admin
    networks:
      - nest-net

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - nest-net

networks:
  nest-net:
    driver: bridge
